[package]
name = "lilium-api-client"
version = "0.1.0"
edition = "2021"

[dependencies]
lilium-common.workspace = true
lilium-models.workspace = true
reqwest = { workspace = true, features = ["cookies", "multipart", "brotli"] }
rand.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
chrono.workspace = true
tungstenite.workspace = true
tokio-tungstenite.workspace = true
futures.workspace = true
url = "2"
