[package]
name = "lilium-database"
version = "0.1.0"
edition = "2024"

[dependencies]
lilium-common.workspace = true
lilium-models.workspace = true
sqlx.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
chrono.workspace = true
serde_json.workspace = true
rust_decimal.workspace = true
dotenvy.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
