[package]
name = "lilium-event-processor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lilium-event-processor"
path = "src/main.rs"

[dependencies]
lilium-common.workspace = true
lilium-models.workspace = true
lilium-database.workspace = true
tokio.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
anyhow.workspace = true
chrono.workspace = true
rand.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
