[package]
name = "lilium-event-processor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lilium-event-processor"
path = "src/main.rs"

[dependencies]
lilium-common.workspace = true
lilium-models.workspace = true
lilium-database.workspace = true
lilium-services.workspace = true
tokio.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sentry.workspace = true
sentry-tracing.workspace = true
anyhow.workspace = true
chrono.workspace = true
rand.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
lilium-test-fixtures.workspace = true
