[package]
name = "lilium-services"
version = "0.1.0"
edition = "2024"

[dependencies]
lilium-common.workspace = true
lilium-models.workspace = true
lilium-api-client.workspace = true
lilium-database.workspace = true
sqlx.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
kamadak-exif.workspace = true
lofty.workspace = true
md-5 = "0.10"

[dev-dependencies]
lilium-test-fixtures.workspace = true
